Repository fga-eps-mds/2022-1-PUMA-Doc, pull requests merged in 2022-07, with the labels that each got.

#28 [#26] Documentando planning da sprint 0
  docs/sprints/sprint0/planning.md
  mkdocs.yml
Labels: documentation, EPS, organização, reunião

#29 [#2] Desenvolvendo Documento - Quadro de Disponibilidade
  docs/assets/imagens/quadro_de_disponibilidade/quadro_disponibilidade_EPS.png
  docs/assets/imagens/quadro_de_disponibilidade/quadro_disponibilidade_MDS.png
  docs/assets/imagens/quadro_de_disponibilidade/quadro_disponibilidade_geral.png
  docs/projeto/quadro_de_disponibilidade.md
  mkdocs.yml
Labels: documentation, organização

#30 [#27] Documentando planning da sprint 0
  docs/sprints/sprint2/planning.md
  mkdocs.yml
Labels: documentation, EPS, organização, reunião

#46 [#39] Adiciona plano de comunicação
  docs/projeto/quadro_de_disponibilidade.md
  mkdocs.yml
Labels: documentação

#42 [#40] Documentar quadro de conhecimento
  docs/projeto/quadro_de_conhecimento.md
  mkdocs.yml
Labels: documentação

#51 Plano de Custos
  docs/projeto/plano_de_custos.md
  mkdocs.yml
Labels: documentação

#58 [#56] Planning Sprint 4
  docs/sprints/planning_template.md
  docs/sprints/sprint4/planning.md
  mkdocs.yml
Labels: documentação

#59 [#14] Planning Sprint 3
  docs/sprints/sprint3/planning.md
  mkdocs.yml
Labels: documentação

#92 [#79] Ajustar Home/ README
  README.md
  docs/index.md
Labels: docs, MDS, easy

#91 [#65] Adiciona documentação do protótipo de alta fidelidade
  .gitignore
  docs/assets/imagens/prototipo_de_alta/cadastro_1.png
  docs/assets/imagens/prototipo_de_alta/cadastro_2.png
  docs/assets/imagens/prototipo_de_alta/detalhes.png
  docs/assets/imagens/prototipo_de_alta/home.png
  docs/assets/imagens/prototipo_de_alta/login.png
  docs/assets/imagens/prototipo_de_alta/popup_iniciar_projeto_1.png
  docs/assets/imagens/prototipo_de_alta/popup_iniciar_projeto_2.png
  docs/produto/prototipo_de_alta.md
  mkdocs.yml
Labels: docs, MDS, medium

#90 [#60] Adiciona o documento de Metodologia
  docs/projeto/metodologia.md
  mkdocs.yml
Labels: docs, EPS

#63 [#62] Adiciona documentação dinâmica
  docs/projeto/plano_de_custos.md
  docs/projeto/plano_de_gerenciamento_de_riscos.md
  docs/projeto/quadro_de_conhecimento.md
  docs/projeto/quadro_de_disponibilidade.md
Labels: bugfix, docs, EPS

#104 [#97] Cria documento do RoadMap
  docs/projeto/roadmap.md
  mkdocs.yml
Labels: documentação
